# Generated by Django 5.0.7 on 2024-07-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=10)),
                ('course_teaching', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=20)),
                ('teacher_id', models.PositiveSmallIntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Year_of_experience', models.PositiveSmallIntegerField()),
                ('account_number', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
