# Generated by Django 5.0.7 on 2024-07-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_name', models.CharField(max_length=10)),
                ('Class_Id', models.IntegerField()),
                ('Number_of_student', models.PositiveSmallIntegerField()),
                ('courses', models.CharField(max_length=20)),
                ('number_of_teachers', models.CharField(max_length=20)),
                ('Room_number', models.PositiveSmallIntegerField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('Class_time', models.CharField(max_length=20)),
                ('Meeting_days', models.CharField(max_length=20)),
                ('Attendance', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
