# Generated by Django 5.0.7 on 2024-07-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classperiod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=10)),
                ('Students_taking', models.IntegerField()),
                ('Course_id', models.IntegerField()),
                ('Class_teacher', models.CharField(max_length=20)),
                ('number_of_teachers', models.CharField(max_length=20)),
                ('Classroom', models.CharField(max_length=10)),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('Academic_year', models.CharField(max_length=20)),
                ('Day_Of_The_Week', models.CharField(max_length=20)),
                ('Capacity', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
