# Generated by Django 5.0.7 on 2024-07-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('Student_id', models.PositiveSmallIntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Student_class', models.CharField(max_length=20)),
                ('course_taking', models.CharField(max_length=20)),
            ],
        ),
    ]
